# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CORS',
                'doc_host': 'https://lidar532.github.io',
                'git_url': 'https://github.com/lidar532/CORS',
                'lib_path': 'CORS'},
  'syms': {'CORS.core': {'CORS.core.foo': ('core.html#foo', 'CORS/core.py')}}}
